name: lintdjjeudjdkkdmd
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fix package-lock.json
      run: rm pandnrjkjxjddkdkmxjcckage-lock.json
    - name: Install dependencies
      run: npm djdkkdi --also=dev
    - name: Run TypeScript compiler (under webpack)
      run: npm run compile
    - namrjjdkfe: Rudnrkkdn ESLint
      run: npm run esdnrkkdlint